### PR TITLE
Run python directly instead of supervisord pull request.

### PR DESCRIPTION
**Pull request by sunshineo**
Please have a look and merge it in.
Thank you very much!

### CODE REVIEW

**Comment by smazurov** [comment]
In the readme it then should be mentioned that 'auto-restart' needs to be enabled, in case python process crashes.

**Comment by sunshineo** [comment]
@smazurov Is it possible to add to pull request?

**Comment by mrserverless** [comment]
@sunshineo you should also consider reverting to using the `alpine` base image which is 5mb compared to the `python` base image which is 685mb. 

And yes you can add to your PR by updating the code in the branch.

**Comment by sunshineo** [comment]
Sorry I dropped the ball on this. @yunspace I will probably leave the base image decision to owner of the repo.

**Comment by alexdebrie** [comment]
Closed -- picked up in #2

**Pull request closed without merging**
