### PR TITLE
New pull request that change to run python directly.

### PR DESCRIPTION
**Pull request by sunshineo**
Also updated README.MD

### CODE REVIEW

**Comment by sunshineo** [comment]
Hello, can someone please pull this in?

**Comment by sunshineo** [comment]
Also, can someone with permission also create a tag after pull in this? So the docker image on docker hub will have a tag and can be fixed.

**Comment by alexdebrie** [comment]
Hi @sunshineo, sorry for the delay. I must have missed this. Are you still interested in this? If so, I'd prefer to keep using the `alpine` image as it's significantly lighter than the `python2.7` image. We could still make the change to run Python directly though, which I agree is a good change.

**Comment by sunshineo** [comment]
Hi @alexdebrie , I'm still interested. I forgot the reason why I had to use python2.7. Probably originally the python installed on top of the alpine image has a version that is not working.

**Comment by alexdebrie** [comment]
For Alpine, I'm guessing you'll need to use the absolute path to Python, so it should be:

```
CMD ["/usr/bin/python", "/code/tutum-schedule.py"]
```

**Comment by sunshineo** [comment]
Please have a look at https://github.com/alexdebrie/tutum-schedule/pull/4
I tested it works.

**Pull request closed without merging**
