### PR TITLE
New pullrequest to change to run python directly

### PR DESCRIPTION
**Pull request by sunshineo**

### CODE REVIEW

**Comment by sunshineo** [comment]
I tested it works.

**Comment by alexdebrie** [comment]
@sunshineo, thanks for your work on this. I just have one small nit -- could you change the CMD to use the exec form? It would be `CMD ["/usr/bin/python" "/code/tutum-schedule.py"]`. This is the [preferred way](https://docs.docker.com/engine/reference/builder/#cmd) for Docker.

**Comment by sunshineo** [comment]
@alexdebrie I changed and tested.

**Comment by alexdebrie** [comment]
Thanks, @sunshineo!

**Pull request merged**
